### ISSUE TITLE
 def check_v2(payload: str, is_debug=False) -> bool: error

### ISSUE THREAD

**Issue by suprajasutti** [aws/aws-imds-packet-analyzer#10]
On running imds_snoop.py, I am getting the below error:

  **File "src/imds_snoop.py", line 25
    def check_v2(payload: str, is_debug=False) -> bool:
                        ^
SyntaxError: invalid syntax**

**Comment by geanboegman** [comment]
I suspect this would be addressed by fix https://github.com/aws/aws-imds-packet-analyzer/commit/a9a4b25f49c6e98b244fddd852ad60f99e74441a, can you please test?  If not, then please share more detail about the instance, kernel and distribution used.  larger log files can also help.

**Comment by liangxiao1** [comment]
Are you running imds_snoop.py in python2? If yes, please try python3 instead. The syntax was implemented in python3([pep-3107](https://peps.python.org/pep-3107/)).

**Comment by suprajasutti** [comment]
![bcc_error](https://github.com/aws/aws-imds-packet-analyzer/assets/129878000/5ec35d32-f8ef-46bc-b163-e21c8e2d5f2b)
@liangxiao1 I was running in Python2.7. However Now I ran in Python 3.10 and I am getting bcc import error
 from bcc import BPF
ImportError: cannot import name 'BPF' from 'bcc' 

I installed bcc with pip installer and it shows requirement statisfied

**Comment by liangxiao1** [comment]
@suprajasutti What's your system version? You might want to try "[install-deps.sh](https://github.com/aws/aws-imds-packet-analyzer/blob/main/install-deps.sh)" with root permission.

**Comment by suprajasutti** [comment]
@liangxiao1 I am running this is ec2 Amazon Linux 2 Kernel 5.10 AMI 2.0.20230906.0 x86_64 HVM gp2 and I ran the sh file. Still getting the error

![image](https://github.com/aws/aws-imds-packet-analyzer/assets/129878000/0724e03d-abf0-4d02-8ba7-6dc209aca61b)

![image](https://github.com/aws/aws-imds-packet-analyzer/assets/129878000/752db203-8dc9-4d26-bbcc-cca381ed30a0)

**Comment by liangxiao1** [comment]
@suprajasutti  I am not sure if your previous pip installation breaks dependency. You might want to try launch a new instance to start it as user guide steps. Thanks
```
$git clone https://github.com/aws/aws-imds-packet-analyzer.git
$sudo ./install-deps.sh
$sudo python3 imds_snoop.py 
```

I works fine in my try with Amazon Linux 2 Kernel 5.10 AMI 2.0.20230906.0 x86_64 HVM gp2.
```
$ uname -r
5.10.192-182.736.amzn2.x86_64
$ sudo python3 imds_snoop.py
Logging to /var/log/imds/imds-trace.log
cannot attach kprobe, probe entry may not exist
cannot attach kprobe, probe entry may not exist
Starting ImdsPacketAnalyzer...
Output format: Info Level:[INFO/ERROR...] IMDS version:[IMDSV1/2?] (pid:[pid]:[process name]:argv:[argv]) -> repeats 3 times for parent process
[WARNING] IMDSv1(!) (pid:24241:curl argv:) called by -> (pid:3079:bash argv:bash) -> (pid:3078:su argv:su) -> (pid:3077:sudo argv:sudo su) Req details: GET /latest/meta-data/ami-id HTTP/1.1, Host: 169.254.169.254, User-Agent: curl/8.3.0, Accept: */*, 
```

**Comment by geanboegman** [comment]
Hi @suprajasutti, I also can not reproduce the error you're seeing, did you try a new instance?

**Comment by geanboegman** [comment]
Resolving issue, can not reproduce
