### ISSUE TITLE
Why is the log being written to an inaccessible place?

### ISSUE THREAD

**Issue by pritster5** [aws/aws-imds-packet-analyzer#12]
/var/log/imds requires super user privileges so the log is not being written to and cannot be read from (without using sudo su).

Why not instead write to the directory where the repo is located or some accessible location that doesn't require sudo privileges?

**Comment by jhmartin** [comment]
Updating https://github.com/aws/aws-imds-packet-analyzer/blob/main/src/imds_snoop.py#L12 would let you write it to alternate locations.

**Comment by geanboegman** [comment]
The trace tool has to run with elevated privileges in order to hook into eBPF, we decided to log at the same level as a precaution.
