### ISSUE TITLE
Container name discovery

### ISSUE THREAD

**Issue by jhmartin** [aws/aws-imds-packet-analyzer#14]
Is there a way this tool could be enhanced to detect if the packet is from a container, and if so log the container name? On ECS/EKS installations it is difficult to track down what application emitted the IMDS1 request. Knowing that 'java' made a IMDS1 call may not help much in identifying the offender.

**Comment by jhmartin** [comment]
Or, if that isn't feasible, a mechanism to pass a 'enrichment' command where the analyzer passes the pid to the enrichment command and appends its output to the log.

**Comment by geanboegman** [comment]
Hi @jhmartin, I'm not aware of a reliable/generic way to detect if the imds call originated in a container.  We would be happy to consider contributions from the broader community, would be great if someone finds a reliable solution.

**Comment by geanboegman** [comment]
Resolving as this is not feasible at the moment.

**Comment by jhmartin** [comment]
Noting that https://www.honeycomb.io/blog/honeycomb-network-agent-kubernetes seems to be able to do the pod mapping  for imds1 on K8S.

**Comment by JBOClara** [comment]
https://github.com/aws/aws-imds-packet-analyzer/issues/1#issuecomment-2704044447
