### ISSUE TITLE
Threat detection

### ISSUE THREAD

**Issue by itaymeller** [aws/aws-imds-packet-analyzer#2]
This is a great tool, and can/should be enhanced to detect threats such as IMDS communications from an unexpected pid/other process identifier for hardened deployments.

IMDSv1 detection available via Cloudtrail as well.

**Comment by geanboegman** [comment]
We do not believe that this trace tool is the right platform for thread detection as the current CW metrics (`metadataNoToken` and `metadataNoTokenRejected`) is a more reliable (off host) source.
