### ISSUE TITLE
[ERROR] {MISSING PAYLOAD} IMDSv1(!) on Ubuntu 22.04

### ISSUE THREAD

**Issue by francesd919** [aws/aws-imds-packet-analyzer#8]
When I run the command below, I got a mix of IMDSv2 calls and [ERROR] {missing payload} errors.
However, in the /var/log/imds/imds-trace.log, everything is [ERROR] {missing payload}.

root@ip-10-209-213-198:/home/ubuntu/aws-imds-packet-analyzer# sudo LD_PRELOAD=/home/ubuntu/bcc/build/src/cc/libbcc.so.0 PYTHONPATH=/home/ubuntu/bcc/build/src/python src/imds_snoop.py
Logging to /var/log/imds/imds-trace.log
cannot attach kprobe, probe entry may not exist
Starting ImdsPacketAnalyzer...
Output format: Info Level:[INFO/ERROR...] IMDS version:[IMDSV1/2?] (pid:[pid]:[process name]:argv:[argv]) -> repeats 3 times for parent process
[INFO] IMDSv2 (pid:440:awsagent argv:/opt/aws/awsagent/bin/awsagent) called by -> (pid:1:systemd argv:/sbin/init) Req details: GET /latest/meta-data/instance-id HTTP/1.1, Host: 169.254.169.254, Accept: */*, Connection: Upgrade, HTTP2-Settings, Upgrade: h2c, HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA, x-aws-ec2-metadata-token: AQAEAPhsawp3bgn_NzX-ESRMQTZiClyj_HerGFpAk66BgVzOf_eFLw==,
[INFO] IMDSv2 (pid:440:awsagent argv:/opt/aws/awsagent/bin/awsagent) called by -> (pid:1:systemd argv:/sbin/init) Req details: GET /latest/dynamic/instance-identity/document HTTP/1.1, Host: 169.254.169.254, Accept: */*, Connection: Upgrade, HTTP2-Settings, Upgrade: h2c, HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA, x-aws-ec2-metadata-token: AQAEAPhsawp3bgn_NzX-ESRMQTZiClyj_HerGFpAk66BgVzOf_eFLw==,
[INFO] IMDSv2 (pid:440:awsagent argv:/opt/aws/awsagent/bin/awsagent) called by -> (pid:1:systemd argv:/sbin/init) Req details: GET /latest/dynamic/instance-identity/signature HTTP/1.1, Host: 169.254.169.254, Accept: */*, Connection: Upgrade, HTTP2-Settings, Upgrade: h2c, HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA, x-aws-ec2-metadata-token: AQAEAPhsawp3bgn_NzX-ESRMQTZiClyj_HerGFpAk66BgVzOf_eFLw==,
[ERROR] {MISSING PAYLOAD} IMDSv1(!) (pid:81267:ssm-agent-worke argv:/snap/amazon-ssm-agent/7983/ssm-agent-worker) called by -> (pid:81156:amazon-ssm-agen argv:/snap/amazon-ssm-agent/7983/amazon-ssm-agent) -> (pid:1:systemd argv:/sbin/init) Req details:

**Comment by geanboegman** [comment]
Addressed by fix https://github.com/aws/aws-imds-packet-analyzer/commit/a9a4b25f49c6e98b244fddd852ad60f99e74441a
